spring:
  application:
    name: order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/hib?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/**.xml
server:
  port: 8082

logging:
  level:
    com:
      hib:
        order:
            dao: debug
env: test
