spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/hib?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
  rabbitmq:
    port: 5672
    host: 192.168.2.138
    password: guest
    username: guest  

mybatis:
  mapper-locations: classpath:mapper/**.xml
logging:
  level:
    com:
     hib:
      product:
       dao: debug
server:
  post: 8082
